sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-8-udemy:latest $DOCKER_USERNAME/rest-with-asp-net-8-udemy:$TRAVIS_JOB_ID
    docker tag rest-with-asp-net-8-udemy-db:latest $DOCKER_USERNAME/rest-with-asp-net-8-udemy-db:$TRAVIS_JOB_ID
    docker push $DOCKER_USERNAME/rest-with-asp-net-8-udemy:$TRAVIS_JOB_ID
    docker push $DOCKER_USERNAME/rest-with-asp-net-8-udemy-db:$TRAVIS_JOB_ID
  on:
    branch: Docker
notifications:
  email:false
